[package]
name = "raytracerinoneweekend"
version = "0.1.0"
authors = ["Danil Kondratiev <knightpp@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"

[profile.release]
panic = "abort"
lto = "thin"